steps:
  # 1. Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:$COMMIT_SHA', '-t', '${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:latest', '.']

  # 2. Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:$COMMIT_SHA']

  # 3. Update K8s Manifests
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i "s|:latest|:$COMMIT_SHA|g" k8s/deployment.yaml

# 4. Migrate (Final: Bash interpolation into URL)
  - name: 'gcr.io/google-appengine/exec-wrapper'
    args:
      - '-i'
      - '${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:$COMMIT_SHA'
      - '-s'
      - '${PROJECT_ID}:${REGION}:${SQL_INSTANCE_NAME}'
      - '--'
      - 'bash'
      - '-c'
      # ВАЖНО: 
      # 1. We use  $$DB_PASS (Cloud Build turns it inot $DB_PASS).
      # 2. We use double qoutes "", so Bash will real password instead of $DB_PASS .
      - 'DATABASE_URL="postgresql://${DB_USER}:$$DB_PASS@/${DB_NAME}?host=/cloudsql/${PROJECT_ID}:${REGION}:${SQL_INSTANCE_NAME}" flask db upgrade'
    secretEnv: ['DB_PASS']
    
  # 5. Deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', '${CLUSTER_NAME}', '--zone', '${ZONE}', '--project', '${PROJECT_ID}']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${CLUSTER_NAME}'

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/sql-password/versions/latest
    env: 'DB_PASS'

options:
  logging: CLOUD_LOGGING_ONLY