steps:
# 1. Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-image'
  args: 
    - 'build'
    - '-t'
    - '$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest'
    - '-t'
    - '$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:__COMMIT_SHA__'
    - '.'

# 2. Push tags
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-latest'
  args: ['push', '$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest']

- name: 'gcr.io/cloud-builders/docker'
  id: 'push-sha'
  args: ['push', '$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:__COMMIT_SHA__']
  
# 4. Update Manifests 
- name: 'ubuntu'
  id: 'update-manifests'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      sed -i "s|__IMAGE_TAG_PLACEHOLDER__|__COMMIT_SHA__|g" k8s/deployment.yaml

# 5. Database Migration
- name: '$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:__COMMIT_SHA__'
  id: 'migrate-db'
  entrypoint: '/bin/bash'
  args:
    - '-c'
    - |
      chmod +x /app/migrate.sh
      /app/migrate.sh
  env:
    - 'INSTANCE_CONNECTION_NAME=__INSTANCE_CONNECTION_NAME__'
  # Load ALL sensitive data from Secret Manager
  secretEnv: ['DB_PASS', 'DB_USER', 'DB_NAME']
  waitFor: ['push-sha'] 

# 6. Deploy to GKE
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'gke-auth'
  args: ['container', 'clusters', 'get-credentials', '$CLUSTER_NAME', '--zone', '$ZONE', '--project', '$PROJECT_ID']
  waitFor: ['migrate-db']

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'kubectl-apply'
  args: ['apply', '-f', 'k8s/']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=$ZONE'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$CLUSTER_NAME'

# Map Secrets to Environment Variables
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/sql-password/versions/latest
    env: 'DB_PASS'
  - versionName: projects/$PROJECT_ID/secrets/sql-user/versions/latest
    env: 'DB_USER'
  - versionName: projects/$PROJECT_ID/secrets/sql-db/versions/latest
    env: 'DB_NAME'

options:
  logging: CLOUD_LOGGING_ONLY