steps:
# 1. Build Docker image (Tag with latest and SHA)
# $REGION, $PROJECT_ID, etc., are fully substituted by the shell script's envsubst.
# __COMMIT_SHA_PH__ is replaced by the literal $COMMIT_SHA by the init_infra.sh script.
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-image'
  args: 
    - 'build'
    - '-t'
    - '$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest'
    - '-t'
    - '$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:__COMMIT_SHA_PH__' # Placeholder for dynamic substitution
    - '.'

# 2. Push the latest tag 
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-latest'
  args: ['push', '$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest']

# 3. Push the SHA tag 
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-sha'
  args: ['push', '$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:__COMMIT_SHA_PH__']
  
# 4. Update K8s Manifests 
- name: 'ubuntu'
  id: 'update-manifests'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Replace the image tag placeholder in deployment.yaml with the literal $COMMIT_SHA.
      # Escaping is required for sed to insert the literal $ into the file.
      sed -i "s|__IMAGE_TAG_PLACEHOLDER__|\\\$$COMMIT_SHA|g" k8s/deployment.yaml

# 5. Cloud SQL Proxy Runner Service (FIXED: using correct positional args and flags)
- name: 'gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0' 
  id: 'sql-proxy-runner'
  args:
    # CRITICAL FIX 1: The instance connection string is a positional argument, not a flag.
    # The '=tcp:5432' part correctly maps the listener port.
    - '$PROJECT_ID:$REGION:$SQL_INSTANCE_NAME=tcp:5432'
    # CRITICAL FIX 2: Use the single correct flag for private IP connectivity in v2.x.
    - '--private-ip' 
    - '-term_timeout=10s' # Keep the existing timeout flag
  waitFor: ['-'] 

# 6. Database Migration Step (Using 'docker run' for reliable execution)
# NOTE: This step still requires a shell (`/bin/bash`) which is why it uses 
# the full Docker image and wraps the execution.
- name: 'gcr.io/cloud-builders/docker' 
  id: 'migrate-db'
  entrypoint: '/bin/bash'
  args:
    - '-c'
    - |
      set -e
      # The image tag now correctly relies on Cloud Build substitution
      IMAGE_URL="$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:__COMMIT_SHA_PH__"
      DB_URL="postgresql://$DB_USER:$DB_PASS@sql-proxy-runner:5432/$DB_NAME"
      
      # Execute the migration command inside the built container image.
      /usr/bin/docker run --rm \
        --network=cloudbuild \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -e DATABASE_URL="${DB_URL}" \
        "${IMAGE_URL}" \
        /bin/bash -c "cd /app && flask db upgrade"
  secretEnv: ['DB_PASS']
  waitFor: ['sql-proxy-runner', 'push-sha'] 

# 7. Deploy to GKE: Authenticate
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'gke-auth'
  args: ['container', 'clusters', 'get-credentials', '$CLUSTER_NAME', '--zone', '$ZONE', '--project', '$PROJECT_ID']
  
# 8. Deploy to GKE: Apply Manifests
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'kubectl-apply'
  args: ['apply', '-f', 'k8s/']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=$ZONE'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$CLUSTER_NAME'

# --- Secret Manager Configuration ---
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/sql-password/versions/latest
    env: 'DB_PASS'

# --- Logging Option ---
options:
  logging: CLOUD_LOGGING_ONLY